---
title: "S-CAP Weekly Report"
author: "Last Updated"
date: '`r format(Sys.time(), "%B %d, %Y %r %Z")`'
output:
  html_document:
    highlight: tango
    theme: spacelab
    toc: yes
    toc_depth: 5
  word_document:
    toc: yes
    toc_depth: '5'
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, comment=NA, fig.width = 6, fig.asp = 0.618, out.width = "80%", fig.align = "center", dev='svg')
```

```{r}
library(openxlsx)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DiagrammeR)
library(ggthemes)
library(scales)
library(DiagrammeRsvg)
library(svglite)
library(rsvg)
library(png)
library(XML)
library(data.table)
library(table1)
```

```{r}
load("h:/scap/scap.Rdata")

setDT(scap)
```

# CONSORT
```{r, fig.width = 10, fig.asp = 0.7, out.width = "100%"}
library(graph)
library(Rgraphviz)

cg.A <- paste("Total Screen 1", "\\\nn=", sum(!is.na(scap$scr1_eligible)), sep = "")
cg.B <- paste("Pre-Eligible", "\\\nn=", sum(scap$scr1_eligible == "Eligible", na.rm = TRUE), sep = "")
cg.C <- paste("Ineligble", "\\\nn=", sum(scap$scr1_eligible == "Ineligible", na.rm = TRUE), sep = "")
cg.D <- paste("Total Screen 2", "\\\nn=", sum(!is.na(scap$screen_2_interview_complete)), sep = "")
cg.E <- paste("Baseline", "\\\nn=", sum(scap$baseline_interview_complete == "Complete", na.rm = TRUE), sep = "")

consort.graph <- ftM2graphNEL(matrix(c(cg.A,cg.A,cg.B,cg.D, 
                                       cg.B,cg.C,cg.D,cg.E), ncol = 2),
                              edgemode="directed")

edges <- buildEdgeList(consort.graph)
nodes <- buildNodeList(consort.graph)

nAttrs <- list()
eAttrs <- list()

Gattrs <- getDefaultAttrs(curAttrs = list(), layoutType = "dot")
Gattrs$graph$margin <- c(0.01,0.01)
# Gattrs$graph$size <- c(10,7)
# Gattrs$graph$rotate <- 90
Gattrs$node$fontsize <- 8
Gattrs$node$shape <- 'rect'
Gattrs$node$fillcolor <- '#C5CCFF'
Gattrs$node$color <- 'transparent'
Gattrs$node$fixedsize <- FALSE
Gattrs$edge$weight <- 2
Gattrs$edge$arrowsize <- 0.5
Gattrs$graph$rankdir <- "TB"

nAttrs$height <- c(1.1, # Total Screen 1
                   1.1, # Screen 1 Pre-Eligible
                   1.1, # Screen 2
                   1.1, # Baseline
                   1.1) # Screen 1 Ineligible

nAttrs$width <- c(2.8, # Total Screen 1
                  2.8, # Screen 1 Pre-Eligible
                  2.8, # Screen 2
                  2.8, # Baseline
                  2.8) # Screen 1 Ineligible

names(nAttrs$height) <- names(nodes)
names(nAttrs$width) <- names(nodes)

plot(consort.graph, attrs = Gattrs, edgeAttrs = eAttrs, nodeAttrs = nAttrs)
```

# Screening
## First Stage
```{r}
table1( ~ ., data = scap[redcap_event_name == "screen_1_arm_1" & screen_1_interview_complete == "Complete", 
                         .(scr1_prescr_consent, scr1_auto_age, scr1_gender, 
                             scr1_genother, scr1_race___c,
                             scr1_ethnicity, scr1_live, 
                             scr1_recruited, scr1_lang, scr1_hivstat, 
                             scr1_incentiveprgm)])
```

## Second Stage
```{r}
table1( ~ ., data = scap[redcap_event_name == "screen_2_arm_1", 
                         .(scr2_labtype, scr2_cd4level, scr2_cd8level,
                           scr2_cd8_cd4ratio, scr2_vlvalue, scr2_vlundect)])
```

# Baseline
```{r}
table1::table1( ~ ., data = scap[redcap_event_name == "baseline_arm_1",
                               .(bl_sexatbirth, bl_sexor, bl_birthplace,
                                 bl_education, bl_income, bl_cemp,
                                 bl_healthinsur_1, bl_livingsit_1,
                                 bl_homeless_nhbs_1, bl_homeless_nhbs_2,
                                 bl_homeless_nhbs_3)])
```



